language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly

matrix:
 allow_failures:
   - julia: nightly

notifications:
  email: andreas@noack.dk

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
